<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>$(RootNamespace).Consumer.IntegrationTests</RootNamespace>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <UseMicrosoftTestingPlatformRunner>true</UseMicrosoftTestingPlatformRunner>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.100.14" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" Version="18.11.2" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.1" />
    <!-- Do not update Verify beyond major version 32: newer major versions require a licence. -->
    <PackageReference Include="Verify.XunitV3" Version="32.0.1" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Consumer/Consumer.csproj" />
  </ItemGroup>
</Project>
