name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

permissions:
  contents: read

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Set up .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
        with:
          dotnet-version: 10.0
      - name: Run Consumer tests
        run: |
          dotnet build tests/Consumer.Tests/Consumer.Tests.csproj
          dotnet test --test-modules tests/Consumer.Tests/bin/Debug/net10.0/Consumer.Tests.dll --no-build
      - name: Run Consumer integration tests
        run: |
          docker compose up -d --wait
          dotnet build tests/Consumer.IntegrationTests/Consumer.IntegrationTests.csproj
          dotnet test --test-modules tests/Consumer.IntegrationTests/bin/Debug/net10.0/Consumer.IntegrationTests.dll --no-build
      - name: Docker Compose logs
        if: always()
        run: docker compose logs
      - name: Stop local environment
        if: always()
        run: docker compose down -v --remove-orphans
      - name: Check Dockerfile Builds
        uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: waste-obligations-notifications:latest
      - name: Check with Trivy
        run: docker run -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:0.74.0@sha256:62b1e65e8869bc4b4c6aa4fa2b21595256c7c2f6018a9d9ad61caf87187c1969 image waste-obligations-notifications:latest --ignore-unfixed

  sonarcloud-scan:
    name: CDP SonarCloud Scan
    permissions:
      contents: read
      pull-requests: read
    uses: ./.github/workflows/sonarcloud.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
